import 'package:flutter/material.dart';

void main() => runApp(const NivecoApp());

class NivecoApp extends StatefulWidget {
  const NivecoApp({super.key});
  @override
  State<NivecoApp> createState() => _NivecoAppState();
}

class _NivecoAppState extends State<NivecoApp> {
  bool gujarati = false;
  bool dark = false;

  @override
  Widget build(BuildContext context) {
    const seed = Color(0xFF6655D9);
    final scheme = ColorScheme.fromSeed(seedColor: seed, brightness: dark ? Brightness.dark : Brightness.light);
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'NIVECO Insights',
      theme: ThemeData(useMaterial3: true, colorScheme: scheme).copyWith(
        scaffoldBackgroundColor: dark ? const Color(0xFF06111F) : const Color(0xFFF8FAFD),
        appBarTheme: AppBarTheme(elevation: 0, surfaceTintColor: Colors.transparent, foregroundColor: dark ? Colors.white : const Color(0xFF111827)),
        cardTheme: CardThemeData(color: dark ? const Color(0xFF0D1B2B) : Colors.white, elevation: 0, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(22), side: BorderSide(color: dark ? const Color(0xFF233B55) : const Color(0xFFE3E8F0)))),
        navigationBarTheme: NavigationBarThemeData(backgroundColor: dark ? const Color(0xFF0B1B2B) : Colors.white, indicatorColor: seed.withValues(alpha: .18)),
        inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: dark ? const Color(0xFF0B1B2B) : Colors.white, border: OutlineInputBorder(borderRadius: BorderRadius.circular(18), borderSide: const BorderSide(color: Color(0xFFD9DFE8)))),
      ),
      home: NivecoShell(gujarati: gujarati, dark: dark, onLanguageChanged: (v) => setState(() => gujarati = v), onThemeChanged: (v) => setState(() => dark = v)),
    );
  }
}

class NivecoWordmark extends StatelessWidget {
  const NivecoWordmark({super.key, required this.dark});
  final bool dark;
  @override
  Widget build(BuildContext context) {
    final ink = dark ? Colors.white : const Color(0xFF07152F);
    return Row(mainAxisSize: MainAxisSize.min, children: [
      Image.asset('assets/niveco-eye.png', width: 54, height: 54, fit: BoxFit.contain),
      const SizedBox(width: 8),
      Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [
        Row(mainAxisSize: MainAxisSize.min, children: [
          Text('NIV', style: TextStyle(color: ink, fontWeight: FontWeight.w900, letterSpacing: 3, fontSize: 27, height: 1)),
          Padding(padding: const EdgeInsets.symmetric(horizontal: 3), child: SizedBox(width: 25, height: 27, child: CustomPaint(painter: _ThreeLineEPainter(ink)))),
          Text('CO', style: TextStyle(color: ink, fontWeight: FontWeight.w900, letterSpacing: 3, fontSize: 27, height: 1)),
        ]),
        const SizedBox(height: 5),
        const Text('IPO & MARKET INSIGHTS', style: TextStyle(fontSize: 9.5, letterSpacing: 1.2, color: Colors.blueGrey, fontWeight: FontWeight.w600)),
      ]),
    ]);
  }
}

class _ThreeLineEPainter extends CustomPainter {
  const _ThreeLineEPainter(this.ink);
  final Color ink;
  @override
  void paint(Canvas canvas, Size size) {
    final p = Paint()..style = PaintingStyle.fill;
    final barHeight = size.height * .20;
    p.color = ink;
    canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(0, 0, size.width, barHeight), const Radius.circular(1.2)), p);
    p.color = const Color(0xFF00CBEA);
    canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(0, (size.height - barHeight) / 2, size.width, barHeight), const Radius.circular(1.2)), p);
    p.color = ink;
    canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(0, size.height - barHeight, size.width, barHeight), const Radius.circular(1.2)), p);
  }
  @override
  bool shouldRepaint(covariant _ThreeLineEPainter oldDelegate) => oldDelegate.ink != ink;
}

class Ipo { const Ipo({required this.id,required this.name,required this.type,required this.status,required this.priceBand,required this.lotSize,required this.subscription,required this.gmp,required this.gmpPct,required this.openDate,required this.closeDate,required this.allotmentDate,required this.listingDate,required this.issueSize,this.listingPrice,this.listingGain}); final String id,name,type,status,priceBand,openDate,closeDate,allotmentDate,listingDate,issueSize; final int lotSize,gmp; final double subscription,gmpPct; final int? listingPrice; final double? listingGain; }
const demoIpos=<Ipo>[Ipo(id:'anawil',name:'Anawil Wire and Engineering',type:'MAINBOARD',status:'Upcoming',priceBand:'₹257–₹270',lotSize:400,subscription:0,gmp:80,gmpPct:29.6,openDate:'03 Aug 2026',closeDate:'05 Aug 2026',allotmentDate:'06 Aug 2026',listingDate:'10 Aug 2026',issueSize:'—'),Ipo(id:'demo-main',name:'Demo Mainboard IPO',type:'MAINBOARD',status:'Open',priceBand:'₹210–₹225',lotSize:65,subscription:7.42,gmp:42,gmpPct:18.7,openDate:'08 Aug 2026',closeDate:'11 Aug 2026',allotmentDate:'12 Aug 2026',listingDate:'14 Aug 2026',issueSize:'₹525 Cr'),Ipo(id:'demo-sme',name:'Demo SME IPO',type:'SME',status:'Upcoming',priceBand:'₹92–₹96',lotSize:1200,subscription:0,gmp:16,gmpPct:16.7,openDate:'12 Aug 2026',closeDate:'14 Aug 2026',allotmentDate:'17 Aug 2026',listingDate:'19 Aug 2026',issueSize:'₹78 Cr'),Ipo(id:'listed-demo',name:'NIVECO Listed Demo',type:'MAINBOARD',status:'Listed',priceBand:'₹300–₹315',lotSize:45,subscription:22.18,gmp:0,gmpPct:0,openDate:'27 Jul 2026',closeDate:'29 Jul 2026',allotmentDate:'30 Jul 2026',listingDate:'03 Aug 2026',issueSize:'₹690 Cr',listingPrice:372,listingGain:18.1)];

class NivecoShell extends StatefulWidget { const NivecoShell({super.key,required this.gujarati,required this.dark,required this.onLanguageChanged,required this.onThemeChanged}); final bool gujarati,dark; final ValueChanged<bool> onLanguageChanged,onThemeChanged; @override State<NivecoShell> createState()=>_NivecoShellState(); }
class _NivecoShellState extends State<NivecoShell>{int index=0;final saved=<String>{};String tr(String en,String gu)=>widget.gujarati?gu:en;@override Widget build(BuildContext context){final pages=[HomeDashboard(gujarati:widget.gujarati,saved:saved,onToggleSaved:toggleSaved),IpoListPage(gujarati:widget.gujarati,saved:saved,onToggleSaved:toggleSaved),CalendarPage(gujarati:widget.gujarati),CalculatorPage(gujarati:widget.gujarati),MorePage(gujarati:widget.gujarati,dark:widget.dark,onThemeChanged:widget.onThemeChanged)];return Scaffold(appBar:AppBar(toolbarHeight:88,backgroundColor:widget.dark?const Color(0xFF071827):Colors.white,titleSpacing:6,title:LayoutBuilder(builder:(context,c)=>SizedBox(width:c.maxWidth,child:Align(alignment:Alignment.centerLeft,child:FittedBox(fit:BoxFit.scaleDown,alignment:Alignment.centerLeft,child:NivecoWordmark(dark:widget.dark))))),actions:[SizedBox(width:42,child:IconButton(padding:EdgeInsets.zero,visualDensity:VisualDensity.compact,onPressed:()=>widget.onThemeChanged(!widget.dark),icon:Icon(widget.dark?Icons.light_mode_outlined:Icons.dark_mode_outlined))),ConstrainedBox(constraints:const BoxConstraints(maxWidth:72),child:TextButton(style:TextButton.styleFrom(padding:const EdgeInsets.symmetric(horizontal:4),minimumSize:Size.zero,tapTargetSize:MaterialTapTargetSize.shrinkWrap),onPressed:()=>widget.onLanguageChanged(!widget.gujarati),child:FittedBox(fit:BoxFit.scaleDown,child:Text(widget.gujarati?'EN':'ગુજરાતી',style:const TextStyle(fontWeight:FontWeight.w700))))),const SizedBox(width:2)],),body:IndexedStack(index:index,children:pages),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:[NavigationDestination(icon:const Icon(Icons.home_outlined),selectedIcon:const Icon(Icons.home),label:tr('Home','હોમ')),NavigationDestination(icon:const Icon(Icons.list_alt_outlined),selectedIcon:const Icon(Icons.list_alt),label:tr('IPOs','IPO')),NavigationDestination(icon:const Icon(Icons.calendar_month_outlined),selectedIcon:const Icon(Icons.calendar_month),label:tr('Calendar','કેલેન્ડર')),NavigationDestination(icon:const Icon(Icons.calculate_outlined),selectedIcon:const Icon(Icons.calculate),label:tr('Calc','કેલ્ક')),NavigationDestination(icon:const Icon(Icons.menu),label:tr('More','વધુ'))]));}void toggleSaved(String id)=>setState(()=>saved.contains(id)?saved.remove(id):saved.add(id));}

class HomeDashboard extends StatefulWidget{const HomeDashboard({super.key,required this.gujarati,required this.saved,required this.onToggleSaved});final bool gujarati;final Set<String> saved;final ValueChanged<String> onToggleSaved;@override State<HomeDashboard> createState()=>_HomeDashboardState();}
class _HomeDashboardState extends State<HomeDashboard>{bool listed=false;String query='';String tr(String en,String gu)=>widget.gujarati?gu:en;@override Widget build(BuildContext context){final items=demoIpos.where((i)=>(listed?i.status=='Listed':i.status!='Listed')&&i.name.toLowerCase().contains(query.toLowerCase())).toList();return ListView(padding:const EdgeInsets.fromLTRB(18,18,18,28),children:[SegmentedButton<bool>(segments:[ButtonSegment(value:false,label:Text(tr('Current & Upcoming','ચાલુ અને આગામી'))),ButtonSegment(value:true,label:Text(tr('Listed','લિસ્ટેડ')))],selected:{listed},onSelectionChanged:(s)=>setState(()=>listed=s.first),showSelectedIcon:false),const SizedBox(height:18),TextField(onChanged:(v)=>setState(()=>query=v),decoration:InputDecoration(hintText:tr('Search IPO company...','IPO કંપની શોધો...'),prefixIcon:const Icon(Icons.search))),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[Container(width:18,height:18,decoration:const BoxDecoration(color:Color(0xFF16C784),shape:BoxShape.circle)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${tr('Live','લાઇવ')} • ${demoIpos.length} ${tr('IPO records','IPO રેકોર્ડ')}',style:const TextStyle(fontWeight:FontWeight.w800,fontSize:18)),Text(tr('Data ready','ડેટા તૈયાર'),style:const TextStyle(color:Colors.blueGrey))])),const Icon(Icons.refresh)]))),const SizedBox(height:10),...items.map((i)=>IpoCard(ipo:i,gujarati:widget.gujarati,saved:widget.saved.contains(i.id),onSave:()=>widget.onToggleSaved(i.id)))]);}}
class IpoListPage extends StatefulWidget{const IpoListPage({super.key,required this.gujarati,required this.saved,required this.onToggleSaved});final bool gujarati;final Set<String> saved;final ValueChanged<String> onToggleSaved;@override State<IpoListPage> createState()=>_IpoListPageState();}
class _IpoListPageState extends State<IpoListPage>{String filter='All';String tr(String en,String gu)=>widget.gujarati?gu:en;@override Widget build(BuildContext context){final items=demoIpos.where((i)=>filter=='All'||i.type==filter||(filter=='Watchlist'&&widget.saved.contains(i.id))).toList();return ListView(padding:const EdgeInsets.all(18),children:[Text(tr('IPO List','IPO યાદી'),style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:14),Wrap(spacing:8,runSpacing:8,children:['All','MAINBOARD','SME','Watchlist'].map((f)=>ChoiceChip(label:Text(f),selected:filter==f,onSelected:(_)=>setState(()=>filter=f))).toList()),const SizedBox(height:16),...items.map((i)=>IpoCard(ipo:i,gujarati:widget.gujarati,saved:widget.saved.contains(i.id),onSave:()=>widget.onToggleSaved(i.id)))]);}}
class IpoCard extends StatelessWidget{const IpoCard({super.key,required this.ipo,required this.gujarati,required this.saved,required this.onSave});final Ipo ipo;final bool gujarati,saved;final VoidCallback onSave;String tr(String en,String gu)=>gujarati?gu:en;@override Widget build(BuildContext context){return Card(margin:const EdgeInsets.only(bottom:14),child:InkWell(borderRadius:BorderRadius.circular(22),onTap:()=>showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(_)=>IpoDetailsSheet(ipo:ipo,gujarati:gujarati)),child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(crossAxisAlignment:CrossAxisAlignment.start,children:[CircleAvatar(radius:26,child:Text(ipo.name.split(' ').where((x)=>x.isNotEmpty).take(2).map((x)=>x[0]).join())),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(ipo.name,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:4),Text('${tr('Offer','ઓફર')}: ${ipo.openDate} – ${ipo.closeDate}',style:const TextStyle(color:Colors.blueGrey))])),Column(children:[Chip(label:Text(ipo.status,style:const TextStyle(fontWeight:FontWeight.w700))),IconButton(onPressed:onSave,icon:Icon(saved?Icons.star:Icons.star_border))])]),const SizedBox(height:18),GridView.count(crossAxisCount:2,childAspectRatio:2.55,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),children:[Stat(label:tr('Offer Price','ઓફર ભાવ'),value:ipo.priceBand),Stat(label:tr('Lot size','લોટ સાઇઝ'),value:'${ipo.lotSize}'),Stat(label:tr('Subscription','સબ્સ્ક્રિપ્શન'),value:'${ipo.subscription.toStringAsFixed(2)}x'),Stat(label:'GMP / Premium',value:'₹${ipo.gmp} (${ipo.gmpPct.toStringAsFixed(1)}%)',positive:ipo.gmp>0),Stat(label:tr('Issue size','ઇશ્યૂ સાઇઝ'),value:ipo.issueSize),Stat(label:tr('Allotment','એલોટમેન્ટ'),value:ipo.allotmentDate)])]))));}}
class Stat extends StatelessWidget{const Stat({super.key,required this.label,required this.value,this.positive=false});final String label,value;final bool positive;@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.all(4),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(color:Colors.blueGrey,fontSize:12)),const SizedBox(height:3),Text(value,style:TextStyle(fontWeight:FontWeight.w800,fontSize:16,color:positive?const Color(0xFF10A66A):null))]));}
class IpoDetailsSheet extends StatelessWidget{const IpoDetailsSheet({super.key,required this.ipo,required this.gujarati});final Ipo ipo;final bool gujarati;String tr(String en,String gu)=>gujarati?gu:en;@override Widget build(BuildContext context){final rows=<MapEntry<String,String>>[MapEntry(tr('Price Band','પ્રાઇસ બેન્ડ'),ipo.priceBand),MapEntry(tr('Lot Size','લોટ સાઇઝ'),'${ipo.lotSize}'),MapEntry(tr('Subscription','સબ્સ્ક્રિપ્શન'),'${ipo.subscription.toStringAsFixed(2)}x'),MapEntry('GMP','₹${ipo.gmp} (${ipo.gmpPct.toStringAsFixed(1)}%)'),MapEntry(tr('Open','ઓપન'),ipo.openDate),MapEntry(tr('Close','ક્લોઝ'),ipo.closeDate),MapEntry(tr('Allotment','એલોટમેન્ટ'),ipo.allotmentDate),MapEntry(tr('Listing','લિસ્ટિંગ'),ipo.listingDate),MapEntry(tr('Issue Size','ઇશ્યૂ સાઇઝ'),ipo.issueSize),if(ipo.listingPrice!=null)MapEntry(tr('Listing Price','લિસ્ટિંગ ભાવ'),'₹${ipo.listingPrice}'),if(ipo.listingGain!=null)MapEntry(tr('Listing Gain','લિસ્ટિંગ ગેઇન'),'${ipo.listingGain}%')];return SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(22,8,22,24),child:ListView(shrinkWrap:true,children:[Text(ipo.name,style:const TextStyle(fontSize:27,fontWeight:FontWeight.w900)),Text('${ipo.type} • ${ipo.status}',style:const TextStyle(color:Colors.blueGrey,fontSize:16)),const Divider(height:30),...rows.map((e)=>Padding(padding:const EdgeInsets.symmetric(vertical:9),child:Row(children:[Expanded(child:Text(e.key,style:const TextStyle(color:Colors.blueGrey,fontSize:16))),Text(e.value,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16))]))),const SizedBox(height:14),Text(tr('Market data must be independently verified before investing.','રોકાણ પહેલાં માર્કેટ ડેટાની સ્વતંત્ર રીતે ચકાસણી કરો.'),style:const TextStyle(color:Colors.blueGrey))])));}}
class CalendarPage extends StatelessWidget{const CalendarPage({super.key,required this.gujarati});final bool gujarati;String tr(String en,String gu)=>gujarati?gu:en;@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(18),children:[Text(tr('IPO Calendar','IPO કેલેન્ડર'),style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:14),...demoIpos.map((i)=>Card(child:ListTile(leading:const Icon(Icons.event),title:Text(i.name),subtitle:Text('${tr('Open','ઓપન')}: ${i.openDate}  •  ${tr('Listing','લિસ્ટિંગ')}: ${i.listingDate}'))))]);}
class CalculatorPage extends StatefulWidget{const CalculatorPage({super.key,required this.gujarati});final bool gujarati;@override State<CalculatorPage> createState()=>_CalculatorPageState();}
class _CalculatorPageState extends State<CalculatorPage>{final price=TextEditingController(text:'270'),lot=TextEditingController(text:'400'),lots=TextEditingController(text:'1');double total=108000;String tr(String en,String gu)=>widget.gujarati?gu:en;void calc()=>setState(()=>total=(double.tryParse(price.text)??0)*(double.tryParse(lot.text)??0)*(double.tryParse(lots.text)??0));@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(18),children:[Text(tr('IPO Investment Calculator','IPO રોકાણ કેલ્ક્યુલેટર'),style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:16),TextField(controller:price,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:tr('Upper price','અપર પ્રાઇસ'))),const SizedBox(height:12),TextField(controller:lot,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:tr('Lot size','લોટ સાઇઝ'))),const SizedBox(height:12),TextField(controller:lots,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:tr('Number of lots','લોટની સંખ્યા'))),const SizedBox(height:16),FilledButton(onPressed:calc,child:Padding(padding:const EdgeInsets.all(14),child:Text(tr('Calculate','ગણતરી કરો')))),const SizedBox(height:18),Text('${tr('Estimated investment','અંદાજિત રોકાણ')}: ₹${total.toStringAsFixed(2)}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w700))]);}
class MorePage extends StatelessWidget{const MorePage({super.key,required this.gujarati,required this.dark,required this.onThemeChanged});final bool gujarati,dark;final ValueChanged<bool> onThemeChanged;String tr(String en,String gu)=>gujarati?gu:en;@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(18),children:[Text(tr('More','વધુ'),style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:14),Card(child:Column(children:[ListTile(leading:const Icon(Icons.star_border),title:Text(tr('Watchlist','વોચલિસ્ટ')),subtitle:Text(tr('Saved IPOs are available from the IPO tab filter.','સેવ કરેલા IPO, IPO ટેબના ફિલ્ટરમાં ઉપલબ્ધ છે.'))),const Divider(height:1),ListTile(leading:const Icon(Icons.admin_panel_settings_outlined),title:Text(tr('Admin Panel','એડમિન પેનલ')),subtitle:Text(tr('Firebase admin migration is the next backend phase.','Firebase admin migration આગળનો backend phase છે.'))),const Divider(height:1),ListTile(leading:const Icon(Icons.download_outlined),title:Text(tr('Export Backup','એક્સપોર્ટ બેકઅપ'))),const Divider(height:1),ListTile(leading:const Icon(Icons.upload_outlined),title:Text(tr('Import Backup','ઇમ્પોર્ટ બેકઅપ'))),const Divider(height:1),SwitchListTile(secondary:const Icon(Icons.contrast),title:Text(tr('Dark mode','ડાર્ક મોડ')),value:dark,onChanged:onThemeChanged)])),const SizedBox(height:22),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[NivecoWordmark(dark:dark),const SizedBox(height:12),Text(tr('Flutter migration base — native Android','Flutter migration base — native Android'),style:const TextStyle(color:Colors.blueGrey)),const Text('Version 1.0.1 • Native NIVECO branding',style:TextStyle(color:Colors.blueGrey))])))]);}
